# SPDX-License-Identifier: Apache-2.0
"""Test-only HMA file connector. Never used inside a timed decode step.

P computes exactly H prompt tokens; D submits the same prefix plus one token,
loads h(H), then computes that last token. All target AND draft cache groups
are saved after the Native runner finalizes speculative decoding.
"""

import hashlib
import json
import math
from dataclasses import dataclass, field
from pathlib import Path

import torch
from safetensors.torch import load_file, save_file
from vllm.distributed.kv_transfer.kv_connector.v1.base import (
    KVConnectorBase_V1, KVConnectorMetadata, KVConnectorRole, SupportsHMA,
)
from vllm.v1.kv_cache_interface import UniformTypeKVCacheSpecs


def token_hash(tokens):
    return hashlib.sha256(json.dumps(list(tokens), separators=(",", ":")).encode()).hexdigest()


def atomic_json(path, data):
    path = Path(path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2) + "\n")
    tmp.replace(path)


def live_blocks(blocks, spec, history):
    """Keep logical indices: SWA holes must never shift the destination pages."""
    end = math.ceil(history / spec.block_size)
    window = getattr(spec, "sliding_window", None)
    start = max(0, end - math.ceil(window / spec.block_size) - 1) if window else 0
    return [(logical, block) for logical, block in enumerate(blocks[:end])
            if logical >= start and block != 0]


@dataclass
class OfflineMetadata(KVConnectorMetadata):
    saves: list[dict] = field(default_factory=list)
    loads: list[dict] = field(default_factory=list)


class OfflineDSV4Connector(KVConnectorBase_V1, SupportsHMA):
    def __init__(self, vllm_config, role, kv_cache_config):
        super().__init__(vllm_config, role, kv_cache_config)
        extra = self._kv_transfer_config.kv_connector_extra_config
        self.root = Path(extra["bank"])
        self.producer = self._kv_transfer_config.is_kv_producer
        self.requests = {}
        self.pending_loads = []
        self.saved = set()
        self.received = set()
        self.caches = {}
        self.dp = vllm_config.parallel_config.data_parallel_rank
        self.tp = 0
        if role == KVConnectorRole.WORKER:
            from vllm.distributed.parallel_state import get_tensor_model_parallel_rank
            self.tp = get_tensor_model_parallel_rank()
        self.specs = {}
        for gid, group in enumerate(kv_cache_config.kv_cache_groups):
            for layer in group.layer_names:
                spec = group.kv_cache_spec
                if isinstance(spec, UniformTypeKVCacheSpecs):
                    spec = spec.kv_cache_specs[layer]
                self.specs[layer] = (gid, spec)

    def register_kv_caches(self, kv_caches):
        if set(kv_caches) != set(self.specs):
            raise ValueError(f"Cache/spec mismatch: {set(kv_caches) ^ set(self.specs)}")
        self.caches = kv_caches

    def _folder(self, key, tp=None):
        # Keys are generated by plan.py, never arbitrary file paths.
        if not key or any(c not in "abcdefghijklmnopqrstuvwxyz0123456789_-" for c in key):
            raise ValueError(f"Invalid offline cache key {key!r}")
        return self.root / key / f"tp{self.tp if tp is None else tp}"

    def get_num_new_matched_tokens(self, request, num_computed_tokens):
        params = request.kv_transfer_params or {}
        key = params.get("offline_key")
        if key is None:
            raise ValueError("Offline validation requires offline_key for every request")
        self.requests[request.request_id] = request
        if self.producer:
            return 0, False
        if num_computed_tokens:
            # No prefix sharing/recompute in this performance fixture.
            raise ValueError("Unexpected local prefix hit or preemption in offline decode")
        manifest = json.loads((self._folder(key, 0) / "manifest.json").read_text())
        prefix = request.prompt_token_ids[:-1]
        if len(prefix) != manifest["history"] or token_hash(prefix) != manifest["token_sha256"]:
            raise ValueError("D prompt does not match the saved P prefix")
        return len(prefix), True

    def update_state_after_alloc(self, request, blocks, num_external_tokens):
        self.requests[request.request_id] = request
        if not self.producer and num_external_tokens:
            self.pending_loads.append({
                "request_id": request.request_id,
                "key": request.kv_transfer_params["offline_key"],
                "blocks": blocks.get_block_ids(),
            })

    def build_connector_meta(self, scheduler_output):
        meta = OfflineMetadata(loads=self.pending_loads)
        self.pending_loads = []
        if self.producer:
            computed = {r.req_id: r.num_computed_tokens for r in scheduler_output.scheduled_new_reqs}
            cached = scheduler_output.scheduled_cached_reqs
            computed.update(zip(cached.req_ids, cached.num_computed_tokens))
            for rid, count in scheduler_output.num_scheduled_tokens.items():
                request = self.requests[rid]
                if rid not in self.saved and computed[rid] + count == request.num_prompt_tokens:
                    state = scheduler_output.kv_connector_block_state
                    if state is None:
                        raise RuntimeError("Pinned Native scheduler must expose live HMA block tables")
                    meta.saves.append({
                        "key": request.kv_transfer_params["offline_key"],
                        "history": request.num_prompt_tokens,
                        "token_sha256": token_hash(request.prompt_token_ids),
                        "blocks": state.get_block_ids(rid),
                    })
                    self.saved.add(rid)
        for rid in scheduler_output.finished_req_ids:
            self.requests.pop(rid, None)
            self.saved.discard(rid)
        return meta

    def request_finished_all_groups(self, request, block_ids):
        # wait_for_save completed synchronously before sampling output returned.
        return False, None

    def _tensors(self):
        for layer, caches in sorted(self.caches.items()):
            if not isinstance(caches, (tuple, list)):
                caches = [caches]
            gid, spec = self.specs[layer]
            for part, cache in enumerate(caches):
                yield f"{layer}__{part}", cache, gid, spec

    def wait_for_save(self):
        if not self.producer or not self.has_connector_metadata():
            return
        for request in self._get_connector_metadata().saves:
            folder = self._folder(request["key"])
            folder.mkdir(parents=True, exist_ok=True)
            if (folder / "manifest.json").exists():
                raise FileExistsError(f"Refusing to overwrite completed cache {folder}")
            tensors, entries = {}, {}
            for name, cache, gid, spec in self._tensors():
                pairs = live_blocks(request["blocks"][gid], spec, request["history"])
                ids = torch.tensor([b for _, b in pairs], dtype=torch.int64, device=cache.device)
                value = cache.index_select(0, ids).cpu().contiguous()
                tensors[name] = value
                entries[name] = {
                    "logical_blocks": [i for i, _ in pairs], "group": gid,
                    "block_size": spec.block_size, "shape": list(value.shape[1:]),
                    "dtype": str(value.dtype), "stride": list(cache.stride()),
                    "sha256": hashlib.sha256(value.view(torch.uint8).numpy().tobytes()).hexdigest(),
                }
            # Save logical contents, including INT8 scales/state, never a raw
            # address dump: P and D allocate different physical block numbers.
            tmp = folder / "cache.safetensors.tmp"
            save_file(tensors, str(tmp))
            tmp.replace(folder / "cache.safetensors")
            atomic_json(folder / "manifest.json", {
                "schema": 1, "history": request["history"],
                "token_sha256": request["token_sha256"], "p_dp_rank": self.dp,
                "p_tp_rank": self.tp, "entries": entries,
            })
            print(f"OFFLINE_CACHE_SAVED {folder} history={request['history']} tensors={len(entries)}", flush=True)

    def start_load_kv(self, forward_context, **kwargs):
        if self.producer:
            return
        for request in self._get_connector_metadata().loads:
            folder = self._folder(request["key"], 0)
            manifest = json.loads((folder / "manifest.json").read_text())
            tensors = load_file(str(folder / "cache.safetensors"))
            local = {name: (cache, gid, spec) for name, cache, gid, spec in self._tensors()}
            if set(local) != set(tensors):
                raise ValueError("P/D target or draft cache layers differ")
            for name, value in tensors.items():
                cache, gid, spec = local[name]
                entry = manifest["entries"][name]
                if (list(cache.shape[1:]) != entry["shape"] or str(cache.dtype) != entry["dtype"]
                        or spec.block_size != entry["block_size"]):
                    raise ValueError(f"TP4→TP1 cache geometry differs: {name}")
                blocks = request["blocks"][gid]
                pairs = [(row, blocks[i]) for row, i in enumerate(entry["logical_blocks"])
                         if i < len(blocks) and blocks[i] != 0]
                expected = {i for i, _ in live_blocks(blocks, spec, manifest["history"])}
                if expected != {entry["logical_blocks"][row] for row, _ in pairs}:
                    raise ValueError(f"Incomplete offline cache: {name}")
                if pairs:
                    rows = torch.tensor([row for row, _ in pairs], dtype=torch.int64)
                    ids = torch.tensor([b for _, b in pairs], dtype=torch.int64, device=cache.device)
                    cache.index_copy_(0, ids, value.index_select(0, rows).to(cache.device))
            torch.npu.synchronize()
            self.received.add(request["request_id"])
            print(f"OFFLINE_CACHE_LOADED dp={self.dp} key={request['key']}", flush=True)

    def get_finished(self, finished_req_ids):
        received, self.received = self.received, set()
        return set(), received

    def wait_for_layer_load(self, layer_name):
        pass

    def save_kv_layer(self, layer_name, kv_layer, attn_metadata, **kwargs):
        pass
